allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  electron: true
  electron-winstaller: true
  esbuild: true
  msw: true
  node-pty: true
  sharp: false

supportedArchitectures:
  os:
    - current
    - darwin
  cpu:
    - x64
    - arm64

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - node-pty

minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.80'
  - '@ai-sdk/react@4.0.102'
  - ai@7.0.99
