import {
  ArrowUp,
  Code,
  GitCommitHorizontal,
  GitPullRequest,
} from "lucide-react";
import { useTranslations } from "next-intl";
import {
  type FormEvent,
  useCallback,
  useEffect,
  useMemo,
  useState,
} from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import type {
  AiProvider,
  ProjectGitCreatePrNextStep,
  ProjectGitCreatePrResponse,
  ProjectGitStatusResponse,
} from "@/types/ide";
import {
  generateCachedProjectPullRequestDetails,
  getCachedProjectPullRequestDetails,
} from "../git-pull-request-details-cache";
import { getPullRequestBranchError } from "./branch-utils";
import {
  ActionError,
  DialogMetricRow,
  GitDialogHeader,
  NextStepSelector,
} from "./dialog-layout";
import { GitDeltaSummary } from "./summary";
import { getStatusFileCount, postJson } from "./utils";

export const CreatePrDialog = ({
  baseBranch: baseBranchOverride = null,
  branch,
  onCompleted,
  onOpenChange,
  open,
  model,
  projectPath,
  provider,
  refreshToken,
  status,
}: {
  baseBranch?: string | null;
  branch: string | null;
  onCompleted: (url: string | null, openPrPage: boolean) => void;
  onOpenChange: (open: boolean) => void;
  open: boolean;
  model: string;
  projectPath: string;
  provider: AiProvider;
  refreshToken: number;
  status: ProjectGitStatusResponse | null;
}) => {
  const commonT = useTranslations("common");
  const gitT = useTranslations("git");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [autoGenerateDetails, setAutoGenerateDetails] = useState(true);
  const [generatedCommitMessage, setGeneratedCommitMessage] = useState<
    string | null
  >(null);
  const [generatingDetails, setGeneratingDetails] = useState(false);
  const [draft, setDraft] = useState(true);
  const [openPrPage, setOpenPrPage] = useState(false);
  const [nextStep, setNextStep] =
    useState<ProjectGitCreatePrNextStep>("create");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const hasChanges = getStatusFileCount(status) > 0;
  const needsPush = !status?.upstreamBranch || (status.aheadCount ?? 0) > 0;
  const baseBranch = baseBranchOverride ?? status?.baseBranch ?? "main";
  const branchError = getPullRequestBranchError(branch, baseBranch, {
    detachedHead: gitT("detachedHeadPrError"),
    sameBranch: (values) => gitT("sameBranchPrError", values),
  });
  const pullRequestChanges = useMemo(() => status?.changes ?? [], [status]);
  const hasDetails = Boolean(title.trim()) && Boolean(description.trim());
  const canCreate = !branchError && !generatingDetails && hasDetails;

  useEffect(() => {
    if (!open) {
      return;
    }

    setTitle("");
    setDescription("");
    setAutoGenerateDetails(true);
    setGeneratedCommitMessage(null);
    setGeneratingDetails(false);
    setDraft(true);
    setOpenPrPage(false);
    setNextStep(
      hasChanges ? "commit-push-create" : needsPush ? "push-create" : "create",
    );
    setError(null);
  }, [hasChanges, needsPush, open]);

  useEffect(() => {
    if (!(open && autoGenerateDetails) || branchError) {
      setGeneratingDetails(false);
      return;
    }

    const params = {
      baseBranch,
      branch,
      changes: pullRequestChanges,
      includeUnstaged: true,
      model,
      nextStep,
      projectPath,
      provider,
      refreshToken,
    };
    const cachedDetails = getCachedProjectPullRequestDetails(params);
    if (cachedDetails !== undefined) {
      setTitle(cachedDetails.title);
      setDescription(cachedDetails.description);
      setGeneratedCommitMessage(cachedDetails.commitMessage);
      setGeneratingDetails(false);
      return;
    }

    let ignore = false;
    setTitle("");
    setDescription("");
    setGeneratedCommitMessage(null);
    setGeneratingDetails(true);
    void generateCachedProjectPullRequestDetails(params)
      .then((details) => {
        if (ignore) {
          return;
        }
        setTitle(details.title);
        setDescription(details.description);
        setGeneratedCommitMessage(details.commitMessage);
      })
      .finally(() => {
        if (!ignore) {
          setGeneratingDetails(false);
        }
      });

    return () => {
      ignore = true;
    };
  }, [
    autoGenerateDetails,
    baseBranch,
    branch,
    branchError,
    nextStep,
    model,
    open,
    projectPath,
    provider,
    pullRequestChanges,
    refreshToken,
  ]);

  const handleAutoGenerateDetailsChange = useCallback(
    (nextChecked: boolean) => {
      setAutoGenerateDetails(nextChecked);
      setGeneratingDetails(false);
      setError(null);
      if (!nextChecked) {
        setTitle("");
        setDescription("");
        setGeneratedCommitMessage(null);
      }
    },
    [],
  );

  const handleSubmit = useCallback(
    async (event: FormEvent<HTMLFormElement>) => {
      event.preventDefault();
      if (submitting || !canCreate) {
        return;
      }
      if (branchError) {
        setError(branchError);
        return;
      }

      setSubmitting(true);
      setError(null);
      try {
        const response = await postJson<ProjectGitCreatePrResponse>(
          "/api/project-git-create-pr",
          {
            baseBranch,
            commitMessage:
              nextStep === "commit-push-create" ? generatedCommitMessage : null,
            description,
            draft,
            includeUnstaged: true,
            nextStep,
            openPrPage,
            projectPath,
            title,
          },
          gitT("unableToCreatePr"),
        );
        onCompleted(response.url, openPrPage);
        onOpenChange(false);
      } catch (error) {
        setError(
          error instanceof Error ? error.message : gitT("unableToCreatePr"),
        );
      } finally {
        setSubmitting(false);
      }
    },
    [
      baseBranch,
      branchError,
      canCreate,
      description,
      draft,
      generatedCommitMessage,
      gitT,
      nextStep,
      onCompleted,
      onOpenChange,
      openPrPage,
      projectPath,
      submitting,
      title,
    ],
  );

  return (
    <Dialog onOpenChange={onOpenChange} open={open}>
      <DialogContent className="max-h-[min(760px,calc(100vh-2rem))] grid-rows-[auto_minmax(0,1fr)] gap-5 overflow-hidden sm:max-w-2xl">
        <GitDialogHeader
          icon={<GitPullRequest />}
          subtitle={
            <>
              {baseBranch} -&gt; {branch ?? gitT("currentBranch")}
            </>
          }
          title={gitT("createPr")}
        />

        <form
          className="min-h-0 space-y-5 overflow-y-auto pr-1"
          onSubmit={handleSubmit}
        >
          <DialogMetricRow
            icon={<Code className="size-4" />}
            label={commonT("changes")}
            value={<GitDeltaSummary status={status} />}
          />

          <label
            className="flex items-center gap-3 text-sm"
            htmlFor="pr-auto-generate-details"
          >
            <Switch
              checked={autoGenerateDetails}
              id="pr-auto-generate-details"
              onCheckedChange={handleAutoGenerateDetailsChange}
            />
            <span>{gitT("autoGeneratePrDetails")}</span>
          </label>

          <div className="space-y-2">
            <label className="font-medium text-sm" htmlFor="pr-title">
              {commonT("title")}
            </label>
            <div className="relative">
              <Input
                aria-busy={generatingDetails}
                id="pr-title"
                onChange={(event) => setTitle(event.target.value)}
                placeholder={generatingDetails ? "" : gitT("enterTitle")}
                readOnly={autoGenerateDetails}
                value={title}
              />
              {generatingDetails ? (
                <div className="pointer-events-none absolute inset-0 flex items-center gap-2 px-3 text-muted-foreground text-sm">
                  <Spinner className="size-4" />
                  <span>{gitT("generatingTitle")}</span>
                </div>
              ) : null}
            </div>
          </div>

          <div className="space-y-2">
            <label className="font-medium text-sm" htmlFor="pr-description">
              {commonT("description")}
            </label>
            <div className="relative">
              <Textarea
                aria-busy={generatingDetails}
                className="h-32 max-h-32 min-h-32 resize-none overflow-y-auto"
                id="pr-description"
                onChange={(event) => setDescription(event.target.value)}
                placeholder={generatingDetails ? "" : gitT("enterDescription")}
                readOnly={autoGenerateDetails}
                value={description}
              />
              {generatingDetails ? (
                <div className="pointer-events-none absolute inset-0 flex items-center justify-center gap-2 text-muted-foreground text-sm">
                  <Spinner className="size-4" />
                  <span>{gitT("generatingDescription")}</span>
                </div>
              ) : null}
            </div>
          </div>

          <div className="space-y-2">
            <div className="font-medium text-sm">{gitT("nextSteps")}</div>
            <NextStepSelector<ProjectGitCreatePrNextStep>
              idPrefix="pr-next-step"
              onValueChange={setNextStep}
              options={[
                {
                  disabled: Boolean(branchError),
                  icon: <GitPullRequest />,
                  label: gitT("createPr"),
                  value: "create",
                },
                {
                  disabled: Boolean(branchError),
                  icon: <ArrowUp />,
                  label: gitT("pushAndCreatePr"),
                  value: "push-create",
                },
                {
                  disabled: !hasChanges || Boolean(branchError),
                  icon: <GitCommitHorizontal />,
                  label: gitT("commitPushAndCreatePr"),
                  value: "commit-push-create",
                },
              ]}
              value={nextStep}
            />
          </div>

          <ActionError error={error ?? branchError} />

          <div className="flex flex-wrap items-center gap-4">
            <label
              className="flex items-center gap-2 text-sm"
              htmlFor="pr-draft"
            >
              <Switch
                checked={draft}
                id="pr-draft"
                onCheckedChange={setDraft}
              />
              <span>{gitT("draft")}</span>
            </label>
            <label
              className="flex items-center gap-2 text-sm"
              htmlFor="pr-open-page"
            >
              <Switch
                checked={openPrPage}
                id="pr-open-page"
                onCheckedChange={setOpenPrPage}
              />
              <span>{gitT("openPrPage")}</span>
            </label>
            <Button
              className="ml-auto min-w-36"
              disabled={submitting || !canCreate}
              type="submit"
            >
              {submitting ? <Spinner className="size-4" /> : null}
              <span>{gitT("createPr")}</span>
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};
